//CONST FOR SEARCH FIELD ACTION
export const CHANGE_SEARCH_FIELD = "CHANGE_SEARCH_FIELD";
//CONST FOR REQUEST MEAL ACITON
export const REQUEST_MEAL_PENDING = "REQUEST_MEAL_PENDING";
export const REQUEST_MEAL_SUCCESS = "REQUEST_MEAL_SUCCESS";
export const REQUEST_MEAL_FAILED = "REQUEST_MEAL_FAILED";
//CONST FOR REQUEST RANDOM MEAL ACTION
export const REQUEST_RANDOM_MEAL_SUCCESS = "REQUEST_RANDOM_MEAL_SUCCESS";
export const REQUEST_RANDOM_MEAL_PENDING = "REQUEST_RANDOM_MEAL_PENDING";
export const REQUEST_RANDOM_MEAL_FAILED = "REQUEST_RANDOM_MEAL_FAILED";
//CONST FOR REQUEST VIEW MEAL ACITON
export const REQUEST_VIEW_MEAL_PENDING = "REQUEST_VIEW_MEAL_PENDING";
export const REQUEST_VIEW_MEAL_SUCCESS = "REQUEST_VIEW_MEAL_SUCCESS";
export const REQUEST_VIEW_MEAL_FAILED = "REQUEST_VIEW_MEAL_FAILED";
